/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.List;

import io.objectbox.Box;
import io.objectbox.query.Query;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    @SuppressWarnings("null")
    public static void main(String[] args) {
        ObjectBox.init();
        Thing t =new Thing();
        t.name="LONG_NAME_";
        Box<Thing> thingBox = ObjectBox.get().boxFor(Thing.class);
        thingBox.put(t);

        Query<Thing> query = thingBox
            .query(Thing_.name.equal("LONG_NAME_"))
            .order(Thing_.name)
             .build();
    
        List<Thing> results = query.find();
        for (Thing thing : results) {
           System.out.println(thing.name); 
        }
        query.close();
        System.out.println("Runs");
    }
}
